name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Install SSH Key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
          echo ${{ secrets.KNOWN_HOSTS }} >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: rsync -chilOrz --stats --exclude .git ./ jannis@jannis.rocks:/var/www/jannis.rocks/public_html/

      - name: Remove SSH
        run: rm -rf ~/.ssh
